/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Character, ControlKeys, Stage, Weapon } from './types';

export const CHARACTERS: Character[] = [
  {
    id: 'kai',
    name: 'Kai',
    title: 'The Cobalt Striker',
    color: '#00ccff',
    darkColor: '#0055aa',
    weaponName: 'Volt Katana',
    specialName: 'Volt Breaker',
    specialDescription: 'Charge forward in a surge of lightning energy dealing multi-hit shockwave damage.',
    stats: {
      speed: 4,
      power: 3,
      defense: 3,
      range: 3,
    },
    weapons: [
      {
        id: 'volt_katana',
        name: 'Volt Katana',
        type: 'light',
        description: 'A finely balanced katana forged in plasma cells. Extremely fast but average punch impact.',
        bonusPower: 0,
        bonusSpeed: 1,
        bonusDefense: 0,
        bonusRange: 0,
        glowColor: '#00ccff',
        visualScale: 1.0,
        spriteType: 'saber',
      },
      {
        id: 'storm_claymore',
        name: 'Storm Greatsword',
        type: 'heavy',
        description: 'A heavy, electrically charged broadsword. Deals devastating cleave damage at the cost of movement speed.',
        bonusPower: 2,
        bonusSpeed: -1,
        bonusDefense: 0,
        bonusRange: 1,
        glowColor: '#3366ff',
        visualScale: 1.35,
        spriteType: 'claymore',
      },
      {
        id: 'shock_gauntlets',
        name: 'Volt Shock Claws',
        type: 'plasma',
        description: 'Dual lightning emitters. Offers unmatched speed and maneuverability at short ranges.',
        bonusPower: -1,
        bonusSpeed: 2,
        bonusDefense: 1,
        bonusRange: -1,
        glowColor: '#00ffcc',
        visualScale: 0.8,
        spriteType: 'claws',
      },
    ],
  },
  {
    id: 'rex',
    name: 'Rex',
    title: 'The Crimson Fury',
    color: '#ff3311',
    darkColor: '#881100',
    weaponName: 'Volcanic Greatsword',
    specialName: 'Meteor Impact',
    specialDescription: 'Pound the ground to summon high-density thermal eruptions underneath the opponent.',
    stats: {
      speed: 2,
      power: 5,
      defense: 4,
      range: 3,
    },
    weapons: [
      {
        id: 'volcanic_sword',
        name: 'Volcanic Greatsword',
        type: 'heavy',
        description: 'A massive heavy sword infused with hyper-compressed magma. Excels in absolute power.',
        bonusPower: 2,
        bonusSpeed: -1,
        bonusDefense: 0,
        bonusRange: 1,
        glowColor: '#ff2200',
        visualScale: 1.4,
        spriteType: 'claymore',
      },
      {
        id: 'magma_mace',
        name: 'Magma Crusher Mace',
        type: 'heavy',
        description: 'A solid spiked core of molten rock. Incredible defensive blocks and blunt kinetic pressure.',
        bonusPower: 1,
        bonusSpeed: -1,
        bonusDefense: 2,
        bonusRange: -1,
        glowColor: '#ff5500',
        visualScale: 1.25,
        spriteType: 'mace',
      },
      {
        id: 'obsidian_halberd',
        name: 'Obsidian Halberd',
        type: 'medium',
        description: 'An elongated glaive forged from volcanic crystal, trading block speed for massive threat range.',
        bonusPower: 1,
        bonusSpeed: 0,
        bonusDefense: -1,
        bonusRange: 2,
        glowColor: '#ff0055',
        visualScale: 1.5,
        spriteType: 'halberd',
      },
    ],
  },
  {
    id: 'luna',
    name: 'Luna',
    title: 'The Void Assassin',
    color: '#bb33ff',
    darkColor: '#5500aa',
    weaponName: 'Astral Dual Blades',
    specialName: 'Phantom Drift',
    specialDescription: 'Unleash a dark void energy beam that punctures opponents at long distance.',
    stats: {
      speed: 5,
      power: 3,
      defense: 2,
      range: 4,
    },
    weapons: [
      {
        id: 'astral_blades',
        name: 'Astral Dual Blades',
        type: 'light',
        description: 'Pair of gravity-defying blades linked directly to Void energy, striking with blistering velocity.',
        bonusPower: 0,
        bonusSpeed: 2,
        bonusDefense: -1,
        bonusRange: 0,
        glowColor: '#bb33ff',
        visualScale: 0.9,
        spriteType: 'twin_daggers',
      },
      {
        id: 'void_scythe',
        name: 'Void Halberd',
        type: 'medium',
        description: 'A dimensional rift scythe weapon. Possesses exceptional range and moderate block deflection.',
        bonusPower: 1,
        bonusSpeed: -1,
        bonusDefense: 1,
        bonusRange: 1,
        glowColor: '#8800ff',
        visualScale: 1.45,
        spriteType: 'halberd',
      },
      {
        id: 'phantom_saber',
        name: 'Phantom Saber',
        type: 'light',
        description: 'An ethereal sword flashing in and out of the real world. Grants perfect balance.',
        bonusPower: 1,
        bonusSpeed: 1,
        bonusDefense: 0,
        bonusRange: -1,
        glowColor: '#ee33ff',
        visualScale: 1.15,
        spriteType: 'saber',
      },
    ],
  },
  {
    id: 'sola',
    name: 'Sola',
    title: 'The Solar Warden',
    color: '#ffcc00',
    darkColor: '#aa7700',
    weaponName: 'Sunstone Claymore',
    specialName: 'Nova Burst',
    specialDescription: 'Surround yourself in a protective solar shield that bursts outwards, dealing heavy counter-damage.',
    stats: {
      speed: 3,
      power: 3,
      defense: 5,
      range: 4,
    },
    weapons: [
      {
        id: 'sunstone_claymore',
        name: 'Sunstone Claymore',
        type: 'heavy',
        description: 'The ancient heavy claymore of the Solar Order, balanced with equal portions of defense and offense.',
        bonusPower: 1,
        bonusSpeed: 0,
        bonusDefense: 1,
        bonusRange: 1,
        glowColor: '#ffaa00',
        visualScale: 1.35,
        spriteType: 'claymore',
      },
      {
        id: 'aurora_saber',
        name: 'Aurora Solar Saber',
        type: 'light',
        description: 'A lightweight sunbeam saber that maximizes attack frequency and agility.',
        bonusPower: -1,
        bonusSpeed: 2,
        bonusDefense: 1,
        bonusRange: -1,
        glowColor: '#ffe600',
        visualScale: 1.05,
        spriteType: 'saber',
      },
      {
        id: 'dawnguard_mace',
        name: 'Dawnguard Flail-Mace',
        type: 'heavy',
        description: 'A stellar warhammer emitting micro-explosions upon landing a block guard, maximizing shield efficiency.',
        bonusPower: 2,
        bonusSpeed: -2,
        bonusDefense: 2,
        bonusRange: 0,
        glowColor: '#ff6600',
        visualScale: 1.3,
        spriteType: 'mace',
      },
    ],
  },
];

export const STAGES: Stage[] = [
  {
    id: 'kyoto',
    name: 'Cyber Kyoto',
    tagline: 'Neon blossoms falling amongst modern pagodas',
    skyTop: '#090518',
    skyBottom: '#190a2b',
    groundTop: '#100624',
    groundBottom: '#040108',
    neonLine: '#ff0055',
    gridLine: 'rgba(255, 0, 85, 0.15)',
    ambientParticleColor: '#ff66aa',
    particleType: 'blossom',
  },
  {
    id: 'sanctuary',
    name: 'Blade Sanctuary',
    tagline: 'Colossal embedded legendary swords in heavy rain',
    skyTop: '#050a12',
    skyBottom: '#0f172a',
    groundTop: '#0d1d33',
    groundBottom: '#020617',
    neonLine: '#00ccff',
    gridLine: 'rgba(0, 204, 255, 0.16)',
    ambientParticleColor: '#e2f1f7',
    particleType: 'rain',
  },
  {
    id: 'forge',
    name: 'Solaris Forge',
    tagline: 'Molten steel background fires and volcanic sparks',
    skyTop: '#1c0500',
    skyBottom: '#2d1400',
    groundTop: '#240600',
    groundBottom: '#090200',
    neonLine: '#ff6600',
    gridLine: 'rgba(255, 102, 0, 0.18)',
    ambientParticleColor: '#ffaa00',
    particleType: 'spark',
  },
];

export const DEFAULT_P1_KEYS: ControlKeys = {
  left: 'KeyA',
  right: 'KeyD',
  up: 'KeyW',
  down: 'KeyS',
  punch: 'KeyF',
  kick: 'KeyG',
  special: 'KeyH',
};

export const DEFAULT_P2_KEYS: ControlKeys = {
  left: 'ArrowLeft',
  right: 'ArrowRight',
  up: 'ArrowUp',
  down: 'ArrowDown',
  punch: 'Numpad1', // Fallbacks handled in input parsing for laptops
  kick: 'Numpad2',
  special: 'Numpad3',
};

// Laptop-friendly fallback secondary controls (useful if players don't have Numpads!)
export const LAPTOP_P2_KEYS: ControlKeys = {
  left: 'ArrowLeft',
  right: 'ArrowRight',
  up: 'ArrowUp',
  down: 'ArrowDown',
  punch: 'Slash',       // /
  kick: 'Period',       // .
  special: 'Comma',     // ,
};
